### ISSUE TITLE
v2.0.6 and v2.0.5 are identical in repository.

### ISSUE THREAD

**Issue by cscott** [smikes/test262-parser#10]
I think perhaps you're missing a commit?  v2.0.6 from npm doesn't seem to be the same as v2.0.5 in the repo.

**Comment by cscott** [comment]
More info: the v2.0.6 release has code to set the `isATest` property, based on the presence of a copyright line.  This new feature appears to be buggy -- the copyright line in `test262/test/built-ins/Promise/length.js` is not properly parsed (for instance), which makes v2.0.6 set `isATest: false`.

**Comment by cscott** [comment]
Seems to be fixed now.

**Comment by smikes** [comment]
I forgot to push after running `npm publish`.

BTW I've added you as a collaborator, since I haven't been able to spend much time on test262 things recently.

**Comment by bterlson** [comment]
@smikes just want to say thanks and that we all miss you :)
