### ISSUE TITLE
Transfer ownership to tc39?

### ISSUE THREAD

**Issue by rwaldron** [smikes/test262-parser#13]
Hi @smikes!

I was wondering if you'd be interested in transferring ownership of test262-parser to tc39? You would obviously retain commit access :) If not, would you be open to adding me as a committer here and as an author for npm (for new releases and such)?

**Comment by smikes** [comment]
Sure, let's start with #2 because it's easier for me to figure out

**Comment by smikes** [comment]
Done -
```
$ npm owner ls test262-parser
rwaldron <waldron.rick@gmail.com>
smikes <smikes@cubane.com>
bterlson <brian.terlson@gmail.com>
```

**Comment by rwaldron** [comment]
@smikes awesome, thanks!
