### ISSUE TITLE
Error when extracting copyright header in a file without a newline at the end

### ISSUE THREAD

**Issue by bterlson** [smikes/test262-parser#8]
Consider the following test case:

```
// blah
assert(true, true);
```

Save, make sure there is no newline, and I get an error on line 75 of parser.js because the match is null.

**Comment by smikes** [comment]
Can you try updating the dependency to 2.0.3 ? I added a test case to test262-parser but I can't reproduce the failure.

**Comment by smikes** [comment]
Actually 2.0.5 ; sorry, I had 2.0.3 local and not pushed/published.  

I'm off to a skate festival, for the rest of the day.

**Comment by bterlson** [comment]
My bad, I didn't realize my deps were so out of date. I'll update test262-harness to depend on ^2.0.5.
